<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="unifi"
    nsURI="http://www.isounifi.org" nsPrefix="unifi">
  <eClassifiers xsi:type="ecore:EClass" name="Diagram" abstract="true" eSuperTypes="#//RepositoryItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="Model" eSuperTypes="#//RepositoryItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="Repository">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dictionary" eType="#//dictionary/DataDictionary"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="catalog" eType="#//catalog/BusinessProcessCatalog"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="#//RepositoryItem"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RepositoryItem" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RegistrationStatus">
    <eLiterals name="OBSOLETE" value="2"/>
    <eLiterals name="PROVISIONALLY_REGISTERED"/>
    <eLiterals name="REGISTERED" value="1"/>
  </eClassifiers>
  <eSubpackages name="catalog" nsURI="http://www.isounifi.org/catalog" nsPrefix="catalog">
    <eClassifiers xsi:type="ecore:EClass" name="BusinessArea" eSuperTypes="#//catalog/CatalogItem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="model" upperBound="-1"
          eType="#//Model" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subDivision" upperBound="-1"
          eType="#//catalog/BusinessArea"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="choreography" upperBound="-1"
          eType="#//catalog/BusinessProcess"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="processDiagram" upperBound="-1"
          eType="#//catalog/BusinessProcessDiagram" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BusinessProcess" eSuperTypes="#//catalog/CatalogItem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="conversation" upperBound="-1"
          eType="#//catalog/BusinessTransaction"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="processDiagram" upperBound="-1"
          eType="#//catalog/BusinessProcessDiagram"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BusinessProcessCatalog">
      <eStructuralFeatures xsi:type="ecore:EReference" name="subDivision" upperBound="-1"
          eType="#//catalog/BusinessArea" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="listing" upperBound="-1"
          eType="#//catalog/CatalogItem" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BusinessProcessDiagram" eSuperTypes="#//Diagram"/>
    <eClassifiers xsi:type="ecore:EClass" name="BusinessTransaction" eSuperTypes="#//catalog/CatalogItem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="participantsRoles" upperBound="-1"
          eType="#//dictionary/businessLayer/BusinessRole"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="interaction" upperBound="-1"
          eType="#//catalog/Interaction"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CatalogItem" abstract="true" eSuperTypes="#//RepositoryItem">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="definition" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="example" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="registration" lowerBound="1"
          eType="#//RegistrationStatus"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="removal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Interaction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="sender" lowerBound="1"
          eType="#//dictionary/businessLayer/BusinessRole"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="receiver" upperBound="-1"
          eType="#//dictionary/businessLayer/BusinessRole"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//catalog/MessageDefinition"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MarketPractice"/>
    <eClassifiers xsi:type="ecore:EClass" name="MessageDefinition" eSuperTypes="#//catalog/CatalogItem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="messageSchema" upperBound="-1"
          eType="#//catalog/SyntaxMessageScheme" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" upperBound="-1"
          eType="#//catalog/MessageRule" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="messageBuildingBlock"
          upperBound="-1" eType="#//dictionary/messageLayer/MessageComponent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="marketPractice" upperBound="-1"
          eType="#//catalog/MarketPractice" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="usage" lowerBound="1"
          upperBound="-1" eType="#//catalog/MessageFunctionality"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MessageDefinitionDiagram" eSuperTypes="#//Diagram"/>
    <eClassifiers xsi:type="ecore:EClass" name="MessageFlowDiagram" eSuperTypes="#//Diagram">
      <eStructuralFeatures xsi:type="ecore:EReference" name="definition" upperBound="-1"
          eType="#//catalog/MessageDefinition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="transaction" upperBound="-1"
          eType="#//catalog/BusinessTransaction"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MessageFunctionality" eSuperTypes="#//catalog/CatalogItem"/>
    <eClassifiers xsi:type="ecore:EClass" name="MessageRule" eSuperTypes="#//catalog/CatalogItem"/>
    <eClassifiers xsi:type="ecore:EClass" name="MessageSet" eSuperTypes="#//catalog/CatalogItem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="description" upperBound="-1"
          eType="#//catalog/MessageDefinition"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SyntaxMessageScheme" eSuperTypes="#//catalog/CatalogItem"/>
  </eSubpackages>
  <eSubpackages name="dictionary" nsURI="http://www.isounifi.org/dictionary" nsPrefix="dictionary">
    <eClassifiers xsi:type="ecore:EClass" name="ComponentTrace">
      <eStructuralFeatures xsi:type="ecore:EReference" name="businessLayer" lowerBound="1"
          eType="#//dictionary/businessLayer/BusinessComponent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="messageLayer" lowerBound="1"
          eType="#//dictionary/messageLayer/MessageComponent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PropertyTrace">
      <eStructuralFeatures xsi:type="ecore:EReference" name="businessLayer" lowerBound="1"
          eType="#//dictionary/businessLayer/BusinessProperty"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="messageLayer" lowerBound="1"
          eType="#//dictionary/messageLayer/MessageElement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataDictionary">
      <eStructuralFeatures xsi:type="ecore:EReference" name="item" upperBound="-1"
          eType="#//dictionary/DictionaryItem" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DictionaryItem" abstract="true" eSuperTypes="#//RepositoryItem">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="definition" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="example" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="registration" lowerBound="1"
          eType="#//RegistrationStatus"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="removalDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="synonym" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eSubpackages name="businessLayer" nsURI="http://www.isounifi.org/dictionary/businessLayer"
        nsPrefix="businessLayer">
      <eClassifiers xsi:type="ecore:EClass" name="BusinessActor" eSuperTypes="#//dictionary/businessLayer/BusinessConcept">
        <eStructuralFeatures xsi:type="ecore:EReference" name="role" lowerBound="1"
            upperBound="-1" eType="#//dictionary/businessLayer/BusinessRole"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="processDiagram" upperBound="-1"
            eType="#//catalog/BusinessProcessDiagram"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="BusinessAssociation" eSuperTypes="#//dictionary/businessLayer/BusinessConcept #//dictionary/businessLayer/BusinessProperty">
        <eStructuralFeatures xsi:type="ecore:EReference" name="endA" lowerBound="1"
            eType="#//dictionary/businessLayer/BusinessComponent"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="endB" lowerBound="1"
            eType="#//dictionary/businessLayer/BusinessComponent"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="BusinessComponent" eSuperTypes="#//dictionary/businessLayer/BusinessConcept">
        <eStructuralFeatures xsi:type="ecore:EReference" name="element" lowerBound="1"
            upperBound="-1" eType="#//dictionary/businessLayer/BusinessElement"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" upperBound="-1"
            eType="#//dictionary/businessLayer/BusinessComponentRule" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="property" upperBound="-1"
            eType="#//dictionary/businessLayer/BusinessProperty"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="BusinessComponentRule" eSuperTypes="#//dictionary/businessLayer/BusinessConcept"/>
      <eClassifiers xsi:type="ecore:EClass" name="BusinessConcept" abstract="true"
          eSuperTypes="#//dictionary/DictionaryItem"/>
      <eClassifiers xsi:type="ecore:EClass" name="BusinessElement" eSuperTypes="#//dictionary/businessLayer/BusinessConcept #//dictionary/businessLayer/BusinessProperty">
        <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
            eType="#//dictionary/dataTypes/DataType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="BusinessElementType" abstract="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="BusinessInformation" abstract="true"
          eSuperTypes="#//dictionary/businessLayer/BusinessConcept"/>
      <eClassifiers xsi:type="ecore:EClass" name="BusinessInformationDiagram" eSuperTypes="#//Diagram">
        <eStructuralFeatures xsi:type="ecore:EReference" name="association" upperBound="-1"
            eType="#//dictionary/businessLayer/BusinessAssociation"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="component" upperBound="-1"
            eType="#//dictionary/businessLayer/BusinessComponent"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="element" upperBound="-1"
            eType="#//dictionary/businessLayer/BusinessElement"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="BusinessModel" eSuperTypes="#//Model #//catalog/CatalogItem">
        <eStructuralFeatures xsi:type="ecore:EReference" name="concept" upperBound="-1"
            eType="#//dictionary/businessLayer/BusinessConcept"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="process" upperBound="-1"
            eType="#//catalog/BusinessProcess"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="BusinessProperty" abstract="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="BusinessRole" eSuperTypes="#//dictionary/businessLayer/BusinessConcept">
        <eStructuralFeatures xsi:type="ecore:EReference" name="concept" upperBound="-1"
            eType="#//catalog/BusinessProcessDiagram"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="dataTypes" nsURI="http://www.isounifi.org/dictionary/dataTypes"
        nsPrefix="dataTypes">
      <eClassifiers xsi:type="ecore:EClass" name="Amount" eSuperTypes="#//dictionary/dataTypes/DataTypeRepresentation"/>
      <eClassifiers xsi:type="ecore:EClass" name="Code" eSuperTypes="#//dictionary/dataTypes/DataTypeRepresentation"/>
      <eClassifiers xsi:type="ecore:EClass" name="DataType" eSuperTypes="#//dictionary/DictionaryItem">
        <eStructuralFeatures xsi:type="ecore:EReference" name="representation" lowerBound="1"
            eType="#//dictionary/dataTypes/DataTypeRepresentation" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DataTypeRepresentation" abstract="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="DateTime" eSuperTypes="#//dictionary/dataTypes/DataTypeRepresentation"/>
      <eClassifiers xsi:type="ecore:EClass" name="Identifier" eSuperTypes="#//dictionary/dataTypes/DataTypeRepresentation"/>
      <eClassifiers xsi:type="ecore:EClass" name="Indicator" eSuperTypes="#//dictionary/dataTypes/DataTypeRepresentation"/>
      <eClassifiers xsi:type="ecore:EClass" name="Quantity" eSuperTypes="#//dictionary/dataTypes/DataTypeRepresentation"/>
      <eClassifiers xsi:type="ecore:EClass" name="Rate" eSuperTypes="#//dictionary/dataTypes/DataTypeRepresentation"/>
      <eClassifiers xsi:type="ecore:EClass" name="Text" eSuperTypes="#//dictionary/dataTypes/DataTypeRepresentation"/>
    </eSubpackages>
    <eSubpackages name="messageLayer" nsURI="http://www.isounifi.org/dictionary/messageLayer"
        nsPrefix="messageLayer">
      <eClassifiers xsi:type="ecore:EClass" name="MessageComponent" eSuperTypes="#//dictionary/messageLayer/MessageConcept">
        <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" upperBound="-1"
            eType="#//dictionary/messageLayer/MessageComponentRule"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="element" lowerBound="1"
            upperBound="-1" eType="#//dictionary/messageLayer/MessageElement"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="MessageComponentRule" eSuperTypes="#//dictionary/messageLayer/MessageConcept"/>
      <eClassifiers xsi:type="ecore:EClass" name="MessageConcept" abstract="true"
          eSuperTypes="#//dictionary/DictionaryItem"/>
      <eClassifiers xsi:type="ecore:EClass" name="MessageElement" eSuperTypes="#//dictionary/messageLayer/MessageConcept">
        <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
            eType="#//dictionary/dataTypes/DataType"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="reversing" nsURI="http://www.isounifi.org/reversing" nsPrefix="reversing">
    <eClassifiers xsi:type="ecore:EClass" name="ConvergenceDocumentation" eSuperTypes="#//RepositoryItem"/>
    <eClassifiers xsi:type="ecore:EClass" name="IndustryMessageSet" eSuperTypes="#//RepositoryItem"/>
    <eClassifiers xsi:type="ecore:EClass" name="ISO15022MessageSet" eSuperTypes="#//reversing/IndustryMessageSet"/>
  </eSubpackages>
</ecore:EPackage>
